#index:
#    path: /
#    controller: App\Controller\DefaultController::index

#Routas para controlador usuario#

user:
    path: /user
    controller: App\Controller\UserController::index
    
register:
    path: /register
    controller: App\Controller\UserController::register
    methods: [POST]
    
login:
    path: /login
    controller: App\Controller\UserController::login
    methods: [POST]
    
edit:
    path: /edit
    controller: App\Controller\UserController::edit
    methods: [PUT]
 

#Routas para controlador Video#

video:
    path: /video
    controller: App\Controller\VideoController::index
    
video_new:
    path: /video/new
    controller: App\Controller\VideoController::create
    methods: [POST]

video_edit:
    path: /video/edit/{id}
    controller: App\Controller\VideoController::create
    methods: [PUT]

video_list:
    path: /video/list
    controller: App\Controller\VideoController::videos
    methods: [GET]
 
video_detail:
    path: /video/detail/{id}
    controller: App\Controller\VideoController::video
    methods: [GET]

remove:
    path: /video/remove/{id}
    controller: App\Controller\VideoController::remove
    methods: [DELETE]